name: BuildRelease

permissions:
  contents: write

on:
  push:
    tags:
      - 'v*'
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    env:
      BUILD_TYPE: Release

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Setup vcpkg
        uses: lukka/run-vcpkg@v11

      - name: Configure CMake
        run: |
          cmake -B build `
            -G "Visual Studio 17 2022" -A x64 `
            -DCMAKE_BUILD_TYPE=${{ env.BUILD_TYPE }} `
            -DCMAKE_TOOLCHAIN_FILE="${{ env.VCPKG_ROOT }}/scripts/buildsystems/vcpkg.cmake" `
            -DVCPKG_TARGET_TRIPLET=x64-windows-static-md

      - name: Build
        run: cmake --build build --config ${{ env.BUILD_TYPE }} --parallel

      - name: Upload release zip
        uses: actions/upload-artifact@v4
        with:
          name: ${{ github.event.repository.name }}-${{ github.sha }}
          path: ${{ github.workspace }}/*-release.zip
          if-no-files-found: error

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          files: ${{ github.workspace }}/*-release.zip

      - name: Locate Release Archive
        id: locate_release
        run: |
          $zip = (Get-ChildItem -Recurse -Filter "*-release.zip").FullName
          echo "zip_path=$zip" >> $env:GITHUB_OUTPUT

      - name: Upload to Nexus Mods
        uses: Nexus-Mods/upload-action@v1.0.0-beta.3
        with:
          api_key: ${{ secrets.NEXUSMODS_API_KEY }}
          file_group_id: ${{ secrets.NEXUSMODS_GROUP_ID }}
          filename: ${{ steps.locate_release.outputs.zip_path }}
          version: ${{ github.ref_name }}
          file_category: main